
query getBlogs($categoryID: String){
  StoreBlogs : blogs(category: $categoryID){
    ...blogFields
  }
}
fragment blogFields on blogType {
  _id
    title
    imageURL
    short_text
    text
  	comments {
      comment
      openToComment
      createdAt
      user {
      	first_name
        last_name
    	}
      answers{
       comment
        user{
          first_name
          last_name
        }
        createdAt
      }
    }
    author {
      first_name
      last_name
    }
    category {
      title
      _id
    }
}