 {
  courses(category : "6279e9afc1e47a98d0f356d6") {
    _id
    title
    text
    imageURL
    short_text
    price
    discount
    category {
      _id
      title
    }
    teacher {
      first_name
      last_name
    }
    chapters {
      title
      episodes {
        title
      }
    }
    comments {
      _id
      comment
      user {
        first_name
        last_name
      }
      answers{
        _id
        comment
        user{
          first_name
          last_name
        }
      }
    }
  }
}